theme: jekyll-theme-minimal
title: noy90 homepage
description: this is test page
color-scheme: auto

sidebar:
  - name: unity作品一覧
    icon: <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
    link: https://noy90.github.io/#unity_game
